#!/bin/sh

#
#    @ File:        commit-msg
#
#    @ Brief:       Git Commit-Msg hook
#
#    @ Description: This script will run after "$ git commit" is finished. For
#                   the commit to go through this script must exit with an exit
#                   status of 0.
#
#    @ Date:        02/02/2024
#

# ----------- ADDS BRANCH NAME AND DESCRIPTION TO COMMIT MESSAGE ------------ #

NAME=$(git branch | grep '*' | sed 's/* //') 
DESCRIPTION=$(git config branch."$NAME".description)

echo "[${NAME}] $(cat $1)" > $1
if [ -n "$DESCRIPTION" ] 
then
   echo "" >> "$1"
   echo $DESCRIPTION >> "$1"
fi 